version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smartcoach
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: smartcoach
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartcoach"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: gunicorn -b 0.0.0.0:8080 'src.app:create_app()'
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - IN_DOCKER=true
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
