version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smartcoach
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: smartcoach
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartcoach"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=8080
    ports:
      - "18081:8080"
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_data:
