# Training Plans Collection
# Research-based marathon training plans for different experience levels and methodologies

# Standardized plan format for GPT training
TRAINING_PLANS = {
    "beginner_6_week": {
        "name": "Research-Based Beginner 6-Week Plan",
        "level": "Beginner",
        "duration_weeks": 6,
        "philosophy": "Gradual mileage buildup with emphasis on completion",
        "training_days": ["MON", "WED", "THU", "SAT"],
        "rest_days": ["TUE", "FRI", "SUN"],
        "weekly_mileage_range": [15, 25],
        "weeks": [
            {
                "week": 1,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 6,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 15,
                "notes": "Foundation building",
            },
            {
                "week": 2,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 8,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 18,
                "notes": "Gradual progression",
            },
            {
                "week": 3,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 10,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 22,
                "notes": "Building endurance",
            },
            {
                "week": 4,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 12,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 25,
                "notes": "Peak training",
            },
            {
                "week": 5,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 14,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 29,
                "notes": "Peak week",
            },
            {
                "week": 6,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 8,
                        "focus": "Taper",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 17,
                "notes": "Taper week",
            },
        ],
    },
    "intermediate_6_week": {
        "name": "Research-Based Intermediate 6-Week Plan",
        "level": "Intermediate",
        "duration_weeks": 6,
        "philosophy": "Balanced training with quality workouts and progressive mileage",
        "training_days": ["MON", "WED", "THU", "SAT"],
        "rest_days": ["TUE", "FRI", "SUN"],
        "weekly_mileage_range": [25, 40],
        "weeks": [
            {
                "week": 1,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 10,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 25,
                "notes": "Foundation building",
            },
            {
                "week": 2,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 12,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 28,
                "notes": "Gradual progression",
            },
            {
                "week": 3,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 14,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 32,
                "notes": "Building endurance",
            },
            {
                "week": 4,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 16,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 35,
                "notes": "Peak training",
            },
            {
                "week": 5,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 18,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 39,
                "notes": "Peak week",
            },
            {
                "week": 6,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 12,
                        "focus": "Taper",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 27,
                "notes": "Taper week",
            },
        ],
    },
    "advanced_6_week": {
        "name": "Research-Based Advanced 6-Week Plan",
        "level": "Advanced",
        "duration_weeks": 6,
        "philosophy": "High-volume training with quality workouts for competitive performance",
        "training_days": ["MON", "WED", "THU", "SAT"],
        "rest_days": ["TUE", "FRI", "SUN"],
        "weekly_mileage_range": [35, 50],
        "weeks": [
            {
                "week": 1,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 12,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 30,
                "notes": "Foundation building",
            },
            {
                "week": 2,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 14,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 35,
                "notes": "Gradual progression",
            },
            {
                "week": 3,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 7,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 16,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 38,
                "notes": "Building endurance",
            },
            {
                "week": 4,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 18,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 42,
                "notes": "Peak training",
            },
            {
                "week": 5,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 9,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 20,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 45,
                "notes": "Peak week",
            },
            {
                "week": 6,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 6,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 14,
                        "focus": "Taper",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 32,
                "notes": "Taper week",
            },
        ],
    },
    "high_mileage_6_week": {
        "name": "Research-Based High-Mileage 6-Week Plan",
        "level": "Advanced",
        "duration_weeks": 6,
        "philosophy": "Maximum volume training for endurance-focused runners",
        "training_days": ["MON", "WED", "THU", "SAT"],
        "rest_days": ["TUE", "FRI", "SUN"],
        "weekly_mileage_range": [45, 65],
        "weeks": [
            {
                "week": 1,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 16,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 40,
                "notes": "Foundation building",
            },
            {
                "week": 2,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 9,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 9,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 9,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 18,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 45,
                "notes": "Gradual progression",
            },
            {
                "week": 3,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 10,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 10,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 10,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 20,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 50,
                "notes": "Building endurance",
            },
            {
                "week": 4,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 11,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 11,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 11,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 22,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 55,
                "notes": "Peak training",
            },
            {
                "week": 5,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 12,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 12,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 12,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 24,
                        "focus": "Endurance",
                        "intensity": "Moderate",
                    },
                ],
                "total_miles": 60,
                "notes": "Peak week",
            },
            {
                "week": 6,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 8,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 16,
                        "focus": "Taper",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 40,
                "notes": "Taper week",
            },
        ],
    },
    "conservative_6_week": {
        "name": "Research-Based Conservative 6-Week Plan",
        "level": "Beginner-Intermediate",
        "duration_weeks": 6,
        "philosophy": "Low-risk training focusing on injury prevention and completion",
        "training_days": ["MON", "WED", "THU", "SAT"],
        "rest_days": ["TUE", "FRI", "SUN"],
        "weekly_mileage_range": [12, 20],
        "weeks": [
            {
                "week": 1,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 2,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 2,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 2,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 4,
                        "focus": "Endurance",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 10,
                "notes": "Very conservative start",
            },
            {
                "week": 2,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 6,
                        "focus": "Endurance",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 15,
                "notes": "Gradual progression",
            },
            {
                "week": 3,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 8,
                        "focus": "Endurance",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 18,
                "notes": "Building endurance",
            },
            {
                "week": 4,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 10,
                        "focus": "Endurance",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 22,
                "notes": "Peak training",
            },
            {
                "week": 5,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 5,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 4,
                        "focus": "Base Building",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 12,
                        "focus": "Endurance",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 25,
                "notes": "Peak week",
            },
            {
                "week": 6,
                "workouts": [
                    {
                        "day": "MON",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "WED",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "THU",
                        "type": "Easy",
                        "miles": 3,
                        "focus": "Recovery",
                        "intensity": "Low",
                    },
                    {
                        "day": "SAT",
                        "type": "Long Run",
                        "miles": 6,
                        "focus": "Taper",
                        "intensity": "Low",
                    },
                ],
                "total_miles": 15,
                "notes": "Taper week",
            },
        ],
    },
}

# Training principles based on research
TRAINING_PRINCIPLES = {
    "progression_rules": {
        "weekly_mileage_increase": "10-15% per week maximum",
        "long_run_percentage": "25-30% of weekly mileage",
        "recovery_weeks": "Every 3-4 weeks, reduce mileage by 20-30%",
        "taper_duration": "2-3 weeks before race",
        "taper_reduction": "Reduce mileage by 50-70% in final weeks",
    },
    "workout_types": {
        "easy_runs": "80% of training volume, conversational pace",
        "long_runs": "Build endurance, longest run 2-3 weeks before race",
        "tempo_runs": "Marathon pace or slightly faster, 20-40 minutes",
        "interval_training": "5K pace or faster, short recovery periods",
        "recovery_runs": "Very easy pace, shorter distance",
    },
    "safety_guidelines": {
        "max_weekly_increase": "15% mileage increase",
        "long_run_max": "Never exceed 25-30% of weekly mileage",
        "consecutive_hard_days": "Maximum 2 consecutive quality days",
        "rest_days": "Minimum 1-2 rest days per week",
        "listen_to_body": "Adjust if experiencing pain or excessive fatigue",
    },
}


def get_plan_summary():
    """Return a summary of all available training plans"""
    summary = {}
    for plan_id, plan_data in TRAINING_PLANS.items():
        summary[plan_id] = {
            "name": plan_data["name"],
            "level": plan_data["level"],
            "weekly_mileage": plan_data["weekly_mileage_range"],
            "philosophy": plan_data["philosophy"],
        }
    return summary


if __name__ == "__main__":
    # Print summary of all plans
    print("Available Training Plans:")
    print("=" * 50)

    summary = get_plan_summary()
    for plan_id, info in summary.items():
        print(f"\n{info['name']}")
        print(f"Level: {info['level']}")
        print(
            f"Weekly Mileage: {info['weekly_mileage'][0]}-{info['weekly_mileage'][1]} miles"
        )
        print(f"Philosophy: {info['philosophy']}")

    print(f"\nTotal Plans Available: {len(TRAINING_PLANS)}")
