# tests/test_training_plan_service.py

import uuid
from datetime import date
import pytest

from src.services import training_plan_service
from src.db.models.user_identity import UserIdentity


@pytest.fixture
def test_user(test_db_session):
    """Insert a user into DB for testing."""
    user_id = uuid.uuid4()
    user = UserIdentity(user_id=user_id, email="runner@example.com")
    test_db_session.add(user)
    test_db_session.commit()
    return user


def test_generate_plan_inserts_plan_and_workouts(
    monkeypatch, test_db_session, test_user
):
    """Ensure generate_plan() persists Plan + PlanWorkouts correctly."""

    # Mock GPT client
    fake_json = """
    {
      "plan_name": "10K Training Plan",
      "notes": "Test plan generated by GPT",
      "workouts": [
        {
          "date": "2025-10-01",
          "workout_type": "Easy Run",
          "description": "30 minutes easy",
          "miles": 3.0,
          "intensity": "Easy"
        },
        {
          "date": "2025-10-03",
          "workout_type": "Tempo Run",
          "description": "5 miles at tempo pace",
          "miles": 5.0,
          "intensity": "Tempo"
        }
      ]
    }
    """

    monkeypatch.setattr(
        "src.services.training_plan_service.call_gpt",
        lambda prompt: fake_json,
    )

    # Run service
    plan = training_plan_service.generate_plan(
        test_db_session,
        user_id=test_user.user_id,
        race_date=date(2025, 12, 1),
        race_distance="10K",
    )

    # Verify plan persisted
    assert plan.id is not None
    assert plan.plan_name == "10K Training Plan"
    assert plan.notes == "Test plan generated by GPT"

    # Verify workouts persisted
    workouts = plan.workouts
    assert len(workouts) == 2
    assert workouts[0].workout_type == "Easy Run"
    assert workouts[1].miles == 5.0
