import uuid
from datetime import date

from src.db.dao import plans_dao
from src.db.models.user_identity import UserIdentity


def test_create_and_get_plan(test_db_session):
    # 🔑 First create a user in user_identity so foreign key is satisfied
    user_id = uuid.uuid4()
    test_db_session.add(UserIdentity(user_id=user_id, email="test@example.com"))
    test_db_session.commit()

    # Now create a plan for that user
    plan_data = {
        "user_id": user_id,
        "plan_name": "Fall Marathon Plan",
        "race_date": date(2025, 12, 1),
        "race_distance": "Marathon",
        "notes": "Generated by GPT",
        "created_by": "gpt",
    }

    plan = plans_dao.create_plan(test_db_session, plan_data)
    test_db_session.commit()

    # Fetch and validate
    fetched = plans_dao.get_plan(test_db_session, plan.id)
    assert fetched is not None
    assert fetched.plan_name == "Fall Marathon Plan"
    assert fetched.user_id == user_id


def test_list_plans_for_user(test_db_session):
    # 🔑 Create two users first (required for FK)
    user_id = uuid.uuid4()
    other_id = uuid.uuid4()
    test_db_session.add_all(
        [
            UserIdentity(user_id=user_id, email="first@example.com"),
            UserIdentity(user_id=other_id, email="other@example.com"),
        ]
    )
    test_db_session.commit()

    # Add plans for both users
    plans_dao.create_plan(
        test_db_session,
        {
            "user_id": user_id,
            "plan_name": "First",
            "race_date": date(2025, 12, 1),
            "race_distance": "Half",
            "notes": "",
            "created_by": "gpt",
        },
    )
    plans_dao.create_plan(
        test_db_session,
        {
            "user_id": other_id,
            "plan_name": "Other",
            "race_date": date(2025, 11, 1),
            "race_distance": "5K",
            "notes": "",
            "created_by": "manual",
        },
    )
    test_db_session.commit()

    # Fetch only plans for user_id
    plans = plans_dao.list_plans_for_user(test_db_session, user_id)

    assert len(plans) == 1
    assert plans[0].plan_name == "First"
