# src/compliance/ai_transparency.py

from typing import Dict, List, Any
from datetime import datetime


class AITransparency:
    """Handle AI transparency and disclosure requirements"""

    @classmethod
    def get_ai_disclosure(cls) -> str:
        """Get AI disclosure text for users"""

        return """
🤖 AI DISCLOSURE

This coaching advice is generated by an AI system (GPT-3.5-turbo) trained on running and coaching data.

IMPORTANT LIMITATIONS:
• This is general coaching advice, not medical advice
• Always consult healthcare professionals for health concerns
• AI responses may contain errors or outdated information
• Use your judgment and listen to your body

DATA USAGE:
• Your running data is used to personalize coaching advice
• Conversations are stored to provide contextual responses
• Data is processed securely and not shared with third parties

For questions about AI usage or data processing, contact our support team.
        """

    @classmethod
    def add_transparency_to_response(
        cls, response: str, context_used: Dict[str, Any]
    ) -> str:
        """Add transparency information to AI responses"""

        transparency_info = f"""
---
{cls.get_ai_disclosure()}

📊 CONTEXT USED:
• Training Plan: {'Yes' if context_used.get('training_plan') else 'No'}
• Recent Activities: {len(context_used.get('activities', []))} activities
• Conversation History: {len(context_used.get('conversation_history', []))} messages
• User Profile: {'Yes' if context_used.get('user_profile') else 'No'}
        """

        return response + transparency_info

    @classmethod
    def get_model_information(cls) -> Dict[str, Any]:
        """Get information about the AI model used"""

        return {
            "model_name": "GPT-3.5-turbo",
            "provider": "OpenAI",
            "training_data": "Pre-trained on diverse text data (cutoff: 2021)",
            "fine_tuning": "No fine-tuning on user data",
            "bias_considerations": "Model may reflect biases in training data",
            "accuracy": "General-purpose model, not specialized for medical advice",
            "last_updated": "2024-01-01",
        }

    @classmethod
    def log_ai_interaction(
        cls,
        user_id: str,
        message: str,
        response: str,
        context_used: Dict[str, Any],
        response_time: float,
    ):
        """Log AI interactions for audit and improvement"""

        interaction_log = {
            "timestamp": datetime.utcnow().isoformat(),
            "user_id": user_id,
            "message_length": len(message),
            "response_length": len(response),
            "context_sources": list(context_used.keys()),
            "response_time_ms": response_time * 1000,
            "model_info": cls.get_model_information(),
        }

        # Log to file or database for audit purposes
        print(f"[AI_INTERACTION_LOG] {interaction_log}")

        return interaction_log
