"""initial schema

Revision ID: 0d9cacbda2b0
Revises: 
Create Date: 2025-06-07 09:06:53.995572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9cacbda2b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('moving_time', sa.Integer(), nullable=True),
    sa.Column('total_elevation_gain', sa.Float(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('suffer_score', sa.Float(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('conv_distance', sa.Float(), nullable=True),
    sa.Column('conv_elevation_feet', sa.Float(), nullable=True),
    sa.Column('conv_avg_speed', sa.Float(), nullable=True),
    sa.Column('conv_max_speed', sa.Float(), nullable=True),
    sa.Column('conv_moving_time', sa.String(), nullable=True),
    sa.Column('conv_elapsed_time', sa.String(), nullable=True),
    sa.Column('hr_zone_1_pct', sa.Float(), nullable=True),
    sa.Column('hr_zone_2_pct', sa.Float(), nullable=True),
    sa.Column('hr_zone_3_pct', sa.Float(), nullable=True),
    sa.Column('hr_zone_4_pct', sa.Float(), nullable=True),
    sa.Column('hr_zone_5_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activities_activity_id'), 'activities', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activities_athlete_id'), 'activities', ['athlete_id'], unique=False)
    op.create_table('tokens',
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('lap_index', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('moving_time', sa.Integer(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=True),
    sa.Column('end_index', sa.Integer(), nullable=True),
    sa.Column('split', sa.Boolean(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('pace_zone', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('conv_distance', sa.Float(), nullable=True),
    sa.Column('conv_avg_speed', sa.Float(), nullable=True),
    sa.Column('conv_moving_time', sa.String(), nullable=True),
    sa.Column('conv_elapsed_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'lap_index', name='uq_activity_lap')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('splits')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_activities_athlete_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
