"""fix split column type to Boolean

Revision ID: 475a80332c46
Revises: 280430412206
Create Date: 2025-06-16 15:05:23.135910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475a80332c46'
down_revision: Union[str, None] = '280430412206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        ALTER TABLE splits 
        ALTER COLUMN split TYPE BOOLEAN 
        USING split::BOOLEAN
    """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('splits', 'split',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
