"""Add structured workout fields to plan_workouts

Revision ID: 66e2d9242637
Revises: be8c3852f634
Create Date: 2025-10-04 21:45:53.972714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66e2d9242637'
down_revision: Union[str, None] = 'be8c3852f634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_activities_user_athletes'), 'activities', type_='foreignkey')
    op.drop_constraint(op.f('fk_activities_user_id'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'user_athletes', ['athlete_id'], ['athlete_id'])
    op.create_foreign_key(None, 'activities', 'user_identity', ['user_id'], ['user_id'])
    op.add_column('plan_workouts', sa.Column('target_zone', sa.String(), nullable=True))
    op.add_column('plan_workouts', sa.Column('target_hr', sa.String(), nullable=True))
    op.add_column('plan_workouts', sa.Column('focus', sa.String(), nullable=True))
    op.add_column('plan_workouts', sa.Column('segments', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('fk_splits_activity'), 'splits', type_='foreignkey')
    op.drop_constraint(op.f('fk_tokens_user_athletes'), 'tokens', type_='foreignkey')
    op.alter_column('user_athletes', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_athletes', 'athlete_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_athletes_athlete_id'), table_name='user_athletes')
    op.drop_index(op.f('ix_user_athletes_user_id'), table_name='user_athletes')
    op.drop_constraint(op.f('fk_user_athletes_user_identity'), 'user_athletes', type_='foreignkey')
    op.create_foreign_key(None, 'user_athletes', 'user_identity', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('user_auth_providers', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('unique_auth_provider'), 'user_auth_providers', type_='unique')
    op.drop_constraint(op.f('unique_provider_user_id'), 'user_auth_providers', type_='unique')
    op.drop_constraint(op.f('uq_user_auth_provider'), 'user_auth_providers', type_='unique')
    op.drop_constraint(op.f('uq_user_auth_providers_full_provider'), 'user_auth_providers', type_='unique')
    op.drop_constraint(op.f('uq_user_auth_providers_user_id'), 'user_auth_providers', type_='unique')
    op.drop_constraint(op.f('fk_user_id'), 'user_auth_providers', type_='foreignkey')
    op.drop_constraint(op.f('unique_email'), 'user_identity', type_='unique')
    op.drop_constraint(op.f('uq_user_identity_email'), 'user_identity', type_='unique')
    op.drop_index(op.f('uq_user_identity_email_not_null'), table_name='user_identity', postgresql_where='(email IS NOT NULL)')
    op.drop_constraint(op.f('uq_user_identity_user_id'), 'user_identity', type_='unique')
    op.alter_column('user_profile', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_profile', 'training_days',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.ARRAY(postgresql.ENUM('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='trainingday')),
               existing_nullable=True)
    op.alter_column('user_profile', 'motivation',
               existing_type=postgresql.ARRAY(postgresql.ENUM('Health', 'Competition', 'StressRelief', 'Enjoyment', 'Other', name='motivation')),
               nullable=True)
    op.drop_constraint(op.f('fk_user_profile_user'), 'user_profile', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_user_profile_user'), 'user_profile', 'user_identity', ['user_id'], ['user_id'])
    op.alter_column('user_profile', 'motivation',
               existing_type=postgresql.ARRAY(postgresql.ENUM('Health', 'Competition', 'StressRelief', 'Enjoyment', 'Other', name='motivation')),
               nullable=False)
    op.alter_column('user_profile', 'training_days',
               existing_type=postgresql.ARRAY(postgresql.ENUM('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='trainingday')),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('user_profile', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_user_identity_user_id'), 'user_identity', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_user_identity_email_not_null'), 'user_identity', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_unique_constraint(op.f('uq_user_identity_email'), 'user_identity', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('unique_email'), 'user_identity', ['email'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('fk_user_id'), 'user_auth_providers', 'user_identity', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_auth_providers_user_id'), 'user_auth_providers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_auth_providers_full_provider'), 'user_auth_providers', ['full_provider_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_auth_provider'), 'user_auth_providers', ['provider_name', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('unique_provider_user_id'), 'user_auth_providers', ['provider_user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('unique_auth_provider'), 'user_auth_providers', ['provider_name', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_auth_providers', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'user_athletes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_athletes_user_identity'), 'user_athletes', 'user_identity', ['user_id'], ['user_id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_user_athletes_user_id'), 'user_athletes', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_athletes_athlete_id'), 'user_athletes', ['athlete_id'], unique=False)
    op.alter_column('user_athletes', 'athlete_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user_athletes', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_tokens_user_athletes'), 'tokens', 'user_athletes', ['athlete_id'], ['athlete_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_splits_activity'), 'splits', 'activities', ['activity_id'], ['activity_id'])
    op.drop_column('plan_workouts', 'segments')
    op.drop_column('plan_workouts', 'focus')
    op.drop_column('plan_workouts', 'target_hr')
    op.drop_column('plan_workouts', 'target_zone')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('fk_activities_user_id'), 'activities', 'user_identity', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_activities_user_athletes'), 'activities', 'user_athletes', ['athlete_id'], ['athlete_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    # ### end Alembic commands ###
