name: Daily Ingestion Cron

on:
  schedule:
    - cron: '0 10,19 * * *'  # Runs daily at 10:00 AM and 7:00 PM UTC
  workflow_dispatch:        # Allows manual trigger

jobs:
  cron-ingestion:
    name: Ingest and Enrich Data
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
      CRON_SECRET_KEY: ${{ secrets.CRON_SECRET_KEY }}
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug DB Token (optional)
        run: python src/scripts/debug_token.py

      - name: Run ingestion + enrichment pipeline
        run: python src/scripts/main_pipeline.py --all --lookback_days=1
