name: Daily Ingestion Cron

on:
  schedule:
    - cron: '0 10,19 * * *'  # Runs daily at 10:00 AM and 7:00 PM UTC
  workflow_dispatch:         # Allows you to trigger it manually

jobs:
  cron-ingestion:
    name: Ingest and Enrich Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load ENV_PROD secret into .env.prod
        run: echo "${{ secrets.ENV_PROD }}" | sed 's/\\n/\n/g' > .env.prod

      - name: Run ingestion + enrichment pipeline
        run: python -m src.scripts.scheduled_ingest
