name: Sync Strava Every 6 Hours (Sandbox)

on:
  schedule:
    - cron: '0 */6 * * *'      # every 6 hours UTC
  workflow_dispatch:          # manual trigger

jobs:
  sync-strava:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger sandbox sync
        run: |
          curl -fsS \
            "https://railway-pg-test-production.up.railway.app/sync-strava-to-db/347085?key=${{ secrets.CRON_SECRET_KEY }}" \
            || echo "Sandbox sync failed!"
